// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSAW_H
#define XSAW_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xsaw_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XSaw_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XSaw;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSaw_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSaw_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSaw_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSaw_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSaw_Initialize(XSaw *InstancePtr, u16 DeviceId);
XSaw_Config* XSaw_LookupConfig(u16 DeviceId);
int XSaw_CfgInitialize(XSaw *InstancePtr, XSaw_Config *ConfigPtr);
#else
int XSaw_Initialize(XSaw *InstancePtr, const char* InstanceName);
int XSaw_Release(XSaw *InstancePtr);
#endif


void XSaw_Set_freq(XSaw *InstancePtr, u32 Data);
u32 XSaw_Get_freq(XSaw *InstancePtr);
void XSaw_Set_vol(XSaw *InstancePtr, u32 Data);
u32 XSaw_Get_vol(XSaw *InstancePtr);
void XSaw_Set_user_writing_V(XSaw *InstancePtr, u32 Data);
u32 XSaw_Get_user_writing_V(XSaw *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
