// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsaw.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSaw_CfgInitialize(XSaw *InstancePtr, XSaw_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSaw_Set_freq(XSaw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSaw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSAW_CTRL_BUS_ADDR_FREQ_DATA, Data);
}

u32 XSaw_Get_freq(XSaw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSaw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSAW_CTRL_BUS_ADDR_FREQ_DATA);
    return Data;
}

void XSaw_Set_vol(XSaw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSaw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSAW_CTRL_BUS_ADDR_VOL_DATA, Data);
}

u32 XSaw_Get_vol(XSaw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSaw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSAW_CTRL_BUS_ADDR_VOL_DATA);
    return Data;
}

void XSaw_Set_user_writing_V(XSaw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSaw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSAW_CTRL_BUS_ADDR_USER_WRITING_V_DATA, Data);
}

u32 XSaw_Get_user_writing_V(XSaw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSaw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSAW_CTRL_BUS_ADDR_USER_WRITING_V_DATA);
    return Data;
}

