// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsaw.h"

extern XSaw_Config XSaw_ConfigTable[];

XSaw_Config *XSaw_LookupConfig(u16 DeviceId) {
	XSaw_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSAW_NUM_INSTANCES; Index++) {
		if (XSaw_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSaw_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSaw_Initialize(XSaw *InstancePtr, u16 DeviceId) {
	XSaw_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSaw_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSaw_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

