// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRL_BUS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of freq
//        bit 31~0 - freq[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of vol
//        bit 31~0 - vol[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of user_writing_V
//        bit 0  - user_writing_V[0] (Read/Write)
//        others - reserved
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSAW_CTRL_BUS_ADDR_FREQ_DATA           0x10
#define XSAW_CTRL_BUS_BITS_FREQ_DATA           32
#define XSAW_CTRL_BUS_ADDR_VOL_DATA            0x18
#define XSAW_CTRL_BUS_BITS_VOL_DATA            32
#define XSAW_CTRL_BUS_ADDR_USER_WRITING_V_DATA 0x20
#define XSAW_CTRL_BUS_BITS_USER_WRITING_V_DATA 1

